name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Image tag"
        required: true
        default: "latest"

  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy webhook
        run: echo "${{ github.event.inputs.tags }}"